receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        # cors:
        #   allowed_origins:
        #     - "http://0.0.0.0:4173"
        #     - "http://0.0.0.0:5173"
        #     - "http://localhost:4173"
        #     - "http://localhost:5173"
        #     - "http://appserver:9999"
        #     - "http://0.0.0.0:8081"
        #     - "http://localhost:9999"
        #   allowed_headers:
        #     - "Access-Control-Request-Headers"
        #     - "Access-Control-Request-Method"
        #     - "content-type"
        #     - "Origin"
        #     - "X-Honeycomb-Team"
processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
