services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    volumes:
      - ${CONFIG_FILE}:/etc/otelcol-contrib/config.yaml
      - ./data:/data
      - ./json-output:/json-output
      - ~/.aws:/root/.aws:ro
    env_file:
      - .env
    environment:
      - AWS_REGION=us-east-1
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
