receivers:
  awss3/source:
    starttime: "2025-10-22 11:00"
    endtime:   "2025-10-22 23:59"
    s3downloader:
      region: us-east-1
      s3_bucket: devreldemo-telemetryarchive-us
      s3_partition: minute   # must match how exporter wrote
    # understands .json (otlp_json) and .binpb (otlp_proto) by default

exporters:
  awss3/dest:
    s3uploader:
      region: us-east-1
      s3_bucket: rimple-perseverating-collector-content
      s3_prefix: json-data
      # choose format you want written to S3 B:
      # marshaler: otlp_json   # or otlp_proto

processors:
  batch: {}

service:
  pipelines:
    traces/time:
      receivers: [awss3/source]
      processors: [batch]
      exporters: [awss3/dest]
    logs/time:
      receivers: [awss3/source]
      processors: [batch]
      exporters: [awss3/dest]


